# Site settings
title: GEDI
email: dubayah@gmail.com
description: >
  Global Ecosystem Dynamics Investigation
baseurl: "/gedi-site"
url: "http://bdubayah.github.io"
twitter_username: GEDI_Knights
github_username:  bdubayah

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
