# Site settings
title: GEDI
email: null
description: >
  Global Ecosystem Dynamics Investigation
baseurl: ""
url: "http://localhost:4000"
twitter_username: GEDI_Knights
github_username:  null

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
